stages:
  - build_docker
  - deploy

variables:
  KUBECONFIG:  /root/.kube/config

docker_image_build_release:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build_docker
  only:
      - tags
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $CI_REGISTRY_IMAGE:latest \
        --build-arg PIZZLY_SETUP_ID=$PIZZLY_SETUP_ID \
        --build-arg PIZZLY_HOST=$PIZZLY_HOST \
        --build-arg CACHE_HOST=$CACHE_HOST \

deploy:
  image: dtzar/helm-kubectl
  stage: deploy
  only:
      - tags
  environment:
    name: production
  before_script:
      - sed -ie "s/deploy-date-value/$(date)/g" kubernetes/deployment.yaml
      - mkdir -p /root/.kube/ && touch /root/.kube/config
      - echo ${KUBERNETES_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
  script:
      - kubectl apply -f kubernetes/deployment.yaml