---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stravaboards-deployment
  namespace: public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stravaboards-workload
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stravaboards-workload
      annotations:
        deploy-date: "deploy-date-value"
    spec:
      containers:
      - name: stravaboards-workload
        image: registry.gitlab.com/oddwes-main/strava-boards
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gitlab-auth